name: codemod
version: 0.3.1
homepage: https://github.com/Workiva/dart_codemod

description: >
  Write and run automated code modifications on a codebase. Primarily geared
  towards updating and refactoring Dart code, but can modify any files.

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  analyzer: ^1.3.0
  args: ^2.0.0
  glob: ^2.0.1
  io: ^1.0.0
  logging: ^1.0.1
  path: ^1.8.0
  quiver: ^3.0.0
  source_span: ^1.8.1
  stack_trace: ^1.10.0
  test: ^1.16.8
  test_descriptor: ^2.0.0

dev_dependencies:
  build_runner: ^1.12.2
  dart_style: ^2.0.0
  # dependency_validator: ^3.0.0
  meta: ^1.3.0
  mockito: ^5.0.3
  pedantic: ^1.11.0
